# On release on master branch, uploads site, raw from 'www' dir, via FTP

name: Publish

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || (!github.event.release.prerelease && github.event.release.target_commitish == 'master') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://ftp.jamiegl.com/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist
